### ISSUE TITLE
Passing tests print distracting output

### ISSUE THREAD

**Issue by samestep** [penrose/penrose#1086]
Currently (commit 1a8b4401fbe65702bc851ebe31f990b5857f3ffe), running `yarn test Domain.test.ts Style.test.ts` in `packages/core/` produces the output shown below, containing some distracting error/warning messages. (No additional output is shown by running just `yarn test`, so it is contained in just these two test files.)

```
yarn run v1.22.19
$ yarn build:parsers
$ nearleyc src/parser/Domain.ne > src/parser/DomainParser.ts && nearleyc src/parser/Substance.ne > src/parser/SubstanceParser.ts && nearleyc src/parser/Style.ne > src/parser/StyleParser.ts
$ jest --watchAll=false
 PASS  src/compiler/Substance.test.ts (6.33 s)
 PASS  src/analysis/SubstanceAnalysis.test.ts (6.795 s)
 PASS  src/compiler/Domain.test.ts
  ● Console

    console.error
      MyOtherType not found in the subtype graph.

      382 |   // TODO: include this case in our error system
      383 |   else {
    > 384 |     console.error(`${subType.name.value} not found in the subtype graph.`);
          |             ^
      385 |     return false;
      386 |   }
      387 | };

      at isDeclaredSubtype (src/compiler/Domain.ts:384:13)
      at isSubtype (src/compiler/Domain.ts:406:26)
      at areSameTypes (src/compiler/Domain.ts:329:19)
      at src/compiler/Domain.ts:316:31
          at Array.some (<anonymous>)
      at checkSymmetricArgs (src/compiler/Domain.ts:316:16)
      at checkStmt (src/compiler/Domain.ts:216:24)
      at src/utils/Error.ts:617:28

    console.error
      MySubType not found in the subtype graph.

      382 |   // TODO: include this case in our error system
      383 |   else {
    > 384 |     console.error(`${subType.name.value} not found in the subtype graph.`);
          |             ^
      385 |     return false;
      386 |   }
      387 | };

      at isDeclaredSubtype (src/compiler/Domain.ts:384:13)
      at isSubtype (src/compiler/Domain.ts:406:26)
      at areSameTypes (src/compiler/Domain.ts:329:19)
      at src/compiler/Domain.ts:316:31
          at Array.some (<anonymous>)
      at checkSymmetricArgs (src/compiler/Domain.ts:316:16)
      at checkStmt (src/compiler/Domain.ts:216:24)
      at src/utils/Error.ts:617:28

 PASS  src/parser/StyleParser.test.ts (7.414 s)
 PASS  src/parser/DomainParser.test.ts
 PASS  src/parser/SubstanceParser.test.ts
 PASS  src/contrib/__tests__/ConstraintsUtils.test.ts
 PASS  src/synthesis/Synthesizer.test.ts
 PASS  src/contrib/SDF.test.ts
 PASS  src/compiler/Style.test.ts (8.306 s)
  ● Console

    console.log
      [warn] [style compiler] Cycles detected in layering order: C, B, A. The system approximated a global layering order instead: A, B, C

      at formatLogObj.width (../../node_modules/consola/dist/consola.js:1:16010)

    console.log
      [warn] [style compiler] Cycles detected in layering order: E, D, B. The system approximated a global layering order instead: A, C, F, B, D, E

      at formatLogObj.width (../../node_modules/consola/dist/consola.js:1:16010)

 PASS  src/synthesis/Mutation.test.ts
 PASS  src/__tests__/mathtransform.test.ts
 PASS  src/contrib/__tests__/ImplicitShapes.test.ts
 PASS  src/engine/Autodiff.test.ts
 PASS  src/contrib/__tests__/Minkowski.test.ts
 PASS  src/contrib/__tests__/Queries.test.ts
 PASS  src/contrib/__tests__/Objectives.test.ts
 PASS  src/contrib/__tests__/ObjectivesUtils.test.ts
 PASS  src/parser/ParserUtil.test.ts
 PASS  src/synthesis/Search.test.ts (9.065 s)
 PASS  src/__tests__/overall.test.ts (9.151 s)
 PASS  src/engine/BBox.test.ts
 PASS  src/contrib/__tests__/Constraints.test.ts (9.443 s)

Test Suites: 23 passed, 23 total
Tests:       508 passed, 508 total
Snapshots:   0 total
Time:        10.277 s
Ran all test suites.
✨  Done in 11.14s.
```

**Comment by samestep** [comment]
From #1109:

> NOTE: this PR doesn't fully resolve https://github.com/penrose/penrose/issues/1086. Still needs to investigate another case of an unwanted console message.

**Comment by samestep** [comment]
Closing in favor of #1214.
