### ISSUE TITLE
containsConvexPolygonPoints with Padding

### ISSUE THREAD

**Issue by liangyiliang** [penrose/penrose#1359]
I think there is a bug in how `padding` is handled in `containsConvexPolygonPoints`.

Here is a test case I wrote.
```typescript
describe("containsConvexPolygonPoints", () => {
  test("test", () => {
    const poly = [
      [0, 0],
      [1, 0],
      [1, 1],
      [0, 1],
    ];
    const pt = [0.25, 0.25];

    expect(
      numsOf([containsConvexPolygonPoints(poly, pt, 0)])[0]
    ).toBeLessThanOrEqual(0);

    expect(
      numsOf([containsConvexPolygonPoints(poly, pt, 0.1)])[0]
    ).toBeLessThanOrEqual(0);

    expect(
      numsOf([containsConvexPolygonPoints(poly, pt, 0.26)])[0]
    ).toBeGreaterThan(0);
  });
});
```

The test case sets up something like this:
![image](https://user-images.githubusercontent.com/16521252/236564175-34c9e69a-11ca-47f1-b034-b55e0c9cb4f4.png)
and wants to check whether the point is in the rectangular polygon under various paddings (0, 0.1, 0.26).

**Expected behavior**
Under padding 0 and 0.1, the point is indeed contained within the polygon, so the `containsConvexPolygonPoints` function should return something <= 0.

Under padding 0.26, the situation looks like: 
![image](https://user-images.githubusercontent.com/16521252/236564672-965d6a35-f5eb-4d1e-a102-0e825cbdfcba.png)
The green-shaded rectangle is the original rectangle under a padding of 0.26. Notice that the point is not within the green rectangle, so `containsConvexPolygonPoints` should return something positive.

**Actual behavior**

In reality, running this test case gives error 
```
  ● containsConvexPolygonPoints › test

    expect(received).toBeGreaterThan(expected)

    Expected: > 0
    Received:   -0.5099975000249998

      29 |     expect(
      30 |       numsOf([containsConvexPolygonPoints(poly, pt, 0.26)])[0]
    > 31 |     ).toBeGreaterThan(0);
         |       ^
      32 |   });
      33 | });
      34 |

      at Object.<anonymous> (src/contrib/__tests__/Minkowski.test.ts:31:7)
      at TestScheduler.scheduleTests (../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (../../node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (../../node_modules/@jest/core/build/cli/index.js:173:3)
```
The third case (under padding 0.26) fails and yields a wrong, negative value.

**Comment by liangyiliang** [comment]
**Hypothesis about what went wrong.**

I don't have a thorough understanding about how Minkowski stuffs work, but I did some calculations.

Function `containsConvexPolygonPoints` is defined as follows:
```
/**
 * Constraint checking whether `point` is inside a convex polygon with vertices `polygonPoints`.
 * @param polygonPoints Sequence of points defining a convex polygon.
 * @param point Testing point.
 * @param padding Padding applied to the polygon.
 */
export const containsConvexPolygonPoints = (
  p1: ad.Num[][],
  p2: ad.Num[],
  padding: ad.Num
): ad.Num => {
  const center = ops.vdiv(p1.reduce(ops.vadd), p1.length);
  // Create a list of all sides given by two subsequent vertices
  const sides = Array.from({ length: p1.length }, (_, key) => key).map((i) => [
    p1[i],
    p1[i > 0 ? i - 1 : p1.length - 1],
  ]);

  const sdfs = sides.map((s: ad.Num[][]) =>
    halfPlaneSDF(s, [ops.vneg(p2)], center, padding)
  );
  return maxN(sdfs);
};
```

It calls `halfPlaneSDF` on each of the four sides, named `s`, of the polygon. We will just consider the left-most side from $(0,1)$ to $(0,0)$, so $s = [[0, 1], [0, 0]]$. The point we want to check, `p2`, is $(.25, .25)$, so `p2 = [.25, .25]`. The center of the polygon is $(.5, .5)$, so `center = [.5, .5]`. We leave `padding` to vary. The call to `halfPlaneSDF` is as follows:
```
halfPlaneSDF(s, [ops.vneg(p2)], center, padding)
-> halfPlaneSDF(
        [[0, 1], [0, 0]],
        [[-.25, -.25]],
        [.5, .5],
        padding
   )
```

Function `halfPlaneSDF`'s source code is as follows:
```
export const halfPlaneSDF = (
  lineSegment: ad.Num[][],
  otherPoints: ad.Num[][],
  insidePoint: ad.Num[],
  padding: ad.Num
): ad.Num => {
  const normal = outwardUnitNormal(lineSegment, insidePoint);
  const alpha = ops.vdot(normal, lineSegment[0]);
  const alphaOther = maxN(otherPoints.map((p) => ops.vdot(normal, p)));
  return neg(addN([alpha, alphaOther, padding]));
};
```
So,
```
lineSegment = [[0, 1], [0, 0]]
otherPoints = [[-.25, -.25]]
insidePoint = [.5, .5],
padding = padding
```

Continuing on, we can compute that `normal = [-1, 0]`. Then,
```
alpha = ops.vdot(normal, lineSegment[0])
      = ops.vdot([-1, 0], [0, 1])
      = 0.
```
Then,
```
alphaOther = ops.vdot([-1, 0], [-.25, -.25])
           = 0.25.
```
Leaving `padding` to vary, the function `halfPlaneSDF` returns
```
-(alpha + alphaOther + padding) = -(0.25 + padding) = -0.25 - padding
```


When is this expression positive? It is negative whenever `padding > -0.25`. So for any positive padding, this function will return a negative value, indicating that the point is within the polygon under that padding. But clearly, that is incorrect.

The solution I can think of is simply make the return value of `halfPlaneSDF` to ```-(alpha + alphaOther) + padding```. In other words, don't distribute the negative sign into `padding`.

**Comment by liangyiliang** [comment]
Concrete example: https://penrose.cs.cmu.edu/try/?gist=3eca5ac60c2eb00f0d41e920672fa9f7

Open the opt panel. Run resample a few times. Clearly, the circle is not contained within the polygon (rectangle) with margin 50. But the opt panel shows nothing wrong.
