### ISSUE TITLE
bug: Programs that work in the IDE can crash when run on command line

### ISSUE THREAD

**Issue by keenancrane** [penrose/penrose#1478]
<img width="926" alt="image" src="https://github.com/penrose/penrose/assets/3604525/b66e66f5-7a0e-4503-8bc4-650225afa58d">

The program below gives an example.  In the IDE it works properly and displays as above.  On the command line it emits the error messages below.  I've also included the trio JSON used to run from the command line, using the invocation `roger trios StarShapedRegion.trio.json --tex-labels -o ./`.

<details>
<summary>StarShapedRegion.trio.json</summary>

```
{
  "substance": "./StarShapedRegion.substance",
  "style": ["./walk-on-spheres.style"],
  "domain": "./walk-on-spheres.domain",
  "variation": "CremaMandrill07835"
}
```
</details>

<details>
<summary>walk-on-spheres.domain</summary>

```
type Domain -- a region in ℝⁿ
predicate hasMixedBoundaryConditions( Domain D )
predicate hasLegend( Domain D )

type Point
predicate isSourceSample( Point p )
constructor closestBoundaryPoint( Domain D, Point p ) -> Point q

type Subdomain
type Ball <: Subdomain
type Star <: Subdomain
constructor sampleBoundary( Subdomain S ) -> Point p
constructor sampleInterior( Subdomain S ) -> Point p

constructor ballAround( Point p ) -> Ball
constructor starAround( Point p ) -> Star
predicate isOffCenter( Ball B ) -- is not centered around p

type NestedPoint
constructor startWalkFrom( Subdomain S ) -> NestedPoint p
constructor nestedBallAround( NestedPoint p ) -> Ball
constructor sampleBoundaryNested( Subdomain S ) -> NestedPoint p

type Ray
constructor toBoundary( Point p, Subdomain S ) -> Ray
```
</details>

<details>
<summary>walk-on-spheres.style</summary>

```
type Domain -- a region in ℝⁿ
predicate hasMixedBoundaryConditions( Domain D )
predicate hasLegend( Domain D )

type Point
predicate isSourceSample( Point p )
constructor closestBoundaryPoint( Domain D, Point p ) -> Point q

type Subdomain
type Ball <: Subdomain
type Star <: Subdomain
constructor sampleBoundary( Subdomain S ) -> Point p
constructor sampleInterior( Subdomain S ) -> Point p

constructor ballAround( Point p ) -> Ball
constructor starAround( Point p ) -> Star
predicate isOffCenter( Ball B ) -- is not centered around p

type NestedPoint
constructor startWalkFrom( Subdomain S ) -> NestedPoint p
constructor nestedBallAround( NestedPoint p ) -> Ball
constructor sampleBoundaryNested( Subdomain S ) -> NestedPoint p

type Ray
constructor toBoundary( Point p, Subdomain S ) -> Ray
```
</details>

<details>
<summary>StarShapedRegion.substance</summary>

```
-- Draw a star-shaped region that does not
-- contain the Neumann boundary.
Domain U
hasMixedBoundaryConditions( U )
-- hasLegend( U )

Point x
Star St := starAround( x )
Ray r1 := toBoundary( x, St )
Ray r2 := toBoundary( x, St )
Ray r3 := toBoundary( x, St )
Ray r4 := toBoundary( x, St )
Ray r5 := toBoundary( x, St )
Ray r6 := toBoundary( x, St )
Ray r7 := toBoundary( x, St )
Ray r8 := toBoundary( x, St )
Ray r9 := toBoundary( x, St )
Ray r10 := toBoundary( x, St )
Ray r11 := toBoundary( x, St )
Ray r12 := toBoundary( x, St )
Ray r13 := toBoundary( x, St )
Ray r14 := toBoundary( x, St )
Ray r15 := toBoundary( x, St )
Ray r16 := toBoundary( x, St )

--Label U $\Omega$
--Label x $x$
--Label St $\text{St}(x)$
```
</details>

Error message:
```
panicked at 'NaN in gradfxs', packages/optimizer/src/lib.rs:681:13

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (file:///Users/keenancrane/Code/penrose/packages/optimizer/build/penrose_optimizer.js:380:21)
    at console_error_panic_hook::hook::h1c8f23b18f19a967 (wasm://wasm/000bb412:wasm-function[116]:0x18633)
    at core::ops::function::Fn::call::he364585372bf890c (wasm://wasm/000bb412:wasm-function[457]:0x21d3a)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/000bb412:wasm-function[188]:0x1dda5)
    at std::panicking::begin_panic_handler::{{closure}}::hfa40135feb109919 (wasm://wasm/000bb412:wasm-function[206]:0x1eba3)
    at std::sys_common::backtrace::__rust_end_short_backtrace::haf21bfec9a028e09 (wasm://wasm/000bb412:wasm-function[451]:0x21d08)
    at rust_begin_unwind (wasm://wasm/000bb412:wasm-function[263]:0x206b3)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/000bb412:wasm-function[288]:0x20de6)
    at penrose_optimizer::step_until::hb07570db7346c7d9 (wasm://wasm/000bb412:wasm-function[55]:0x5aad)
    at penrose_step_until (wasm://wasm/000bb412:wasm-function[154]:0x1bc67)


roger trios [trios..]

Create diagrams from multiple .trio.json files.

Options:
      --version     Show version number                                [boolean]
      --help        Show help                                          [boolean]
      --trios       Any number of .trio.json files of Penrose trios.
                                                              [array] [required]
      --tex-labels  Render Equation shapes as plain TeX strings in the output SV
                    G                                 [boolean] [default: false]
  -o, --out         Output folder containing the SVG files   [string] [required]

RuntimeError: unreachable
    at __rust_start_panic (wasm://wasm/000bb412:wasm-function[481]:0x21df5)
    at rust_panic (wasm://wasm/000bb412:wasm-function[313]:0x212b5)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/000bb412:wasm-function[188]:0x1ddd0)
    at std::panicking::begin_panic_handler::{{closure}}::hfa40135feb109919 (wasm://wasm/000bb412:wasm-function[206]:0x1eba3)
    at std::sys_common::backtrace::__rust_end_short_backtrace::haf21bfec9a028e09 (wasm://wasm/000bb412:wasm-function[451]:0x21d08)
    at rust_begin_unwind (wasm://wasm/000bb412:wasm-function[263]:0x206b3)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/000bb412:wasm-function[288]:0x20de6)
    at penrose_optimizer::step_until::hb07570db7346c7d9 (wasm://wasm/000bb412:wasm-function[55]:0x5aad)
    at penrose_step_until (wasm://wasm/000bb412:wasm-function[154]:0x1bc67)
    at penrose_step_until (file:///Users/keenancrane/Code/penrose/packages/optimizer/build/penrose_optimizer.js:249:22)
```

**Comment by keenancrane** [comment]
Something else I don't understand here is that the number of varying variable is always 6, and the optimizer always computes a gradient of length 6, even if I set all the floating-point valued fields of the shape (`center`, `r`, `fillColor`, `strokeColor`, `strokeWidth`) to constants:

<img width="109" alt="image" src="https://github.com/penrose/penrose/assets/3604525/156741df-ec47-453e-964e-44cfa425406e">

If I remove the shape altogether, then these varying variables go away, and the gradient length becomes zero.

**Comment by keenancrane** [comment]
Changed the name of title of this issue, because it appears to be unrelated to CLI.  The issue is simply that the optimizer breaks (panics) if there are no constraints.

Here's a better minimal example, which does have an objective, but doesn't have any constraints (and still causes trouble):

```
canvas {
   width = 100
   height = 100

   shape C = Circle {
      ensureOnCanvas: false
   }
   
   encourage norm(C.center) == 0
}
```

Here's the Chrome console log:

```
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
000bb412:0x1870f panicked at 'NaN in gradfxs', packages/optimizer/src/lib.rs:681:13

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://127.0.0.1:3000/try/node_modules/.vite/deps/@penrose_optimizer.js?v=1bdb9ceb:336:17)
    at console_error_panic_hook::hook::h1c8f23b18f19a967 (wasm://wasm/000bb412:wasm-function[116]:0x18633)
    at core::ops::function::Fn::call::he364585372bf890c (wasm://wasm/000bb412:wasm-function[457]:0x21d3a)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (wasm://wasm/000bb412:wasm-function[188]:0x1dda5)
    at std::panicking::begin_panic_handler::{{closure}}::hfa40135feb109919 (wasm://wasm/000bb412:wasm-function[206]:0x1eba3)
    at std::sys_common::backtrace::__rust_end_short_backtrace::haf21bfec9a028e09 (wasm://wasm/000bb412:wasm-function[451]:0x21d08)
    at rust_begin_unwind (wasm://wasm/000bb412:wasm-function[263]:0x206b3)
    at core::panicking::panic_fmt::he4489d678d6570d5 (wasm://wasm/000bb412:wasm-function[288]:0x20de6)
    at penrose_optimizer::step_until::hb07570db7346c7d9 (wasm://wasm/000bb412:wasm-function[55]:0x5aad)
    at penrose_step_until (wasm://wasm/000bb412:wasm-function[154]:0x1bc67)


imports.wbg.__wbg_error_f851667af71bcfc6 @ penrose_optimizer.js:392
$console_error_panic_hook::hook::h1c8f23b18f19a967 @ 000bb412:0x1870f
$core::ops::function::Fn::call::he364585372bf890c @ 000bb412:0x21d3a
$std::panicking::rust_panic_with_hook::h7f7102b82d51338f @ 000bb412:0x1dda5
$std::panicking::begin_panic_handler::{{closure}}::hfa40135feb109919 @ 000bb412:0x1eba3
$std::sys_common::backtrace::__rust_end_short_backtrace::haf21bfec9a028e09 @ 000bb412:0x21d08
$rust_begin_unwind @ 000bb412:0x206b3
$core::panicking::panic_fmt::he4489d678d6570d5 @ 000bb412:0x20de6
$penrose_optimizer::step_until::hb07570db7346c7d9 @ 000bb412:0x5aad
$penrose_step_until @ 000bb412:0x1bc67
penrose_step_until @ penrose_optimizer.js:249
stepUntil @ source.ts:61
step @ index.ts:58
stepTimes @ index.ts:86
step @ DiagramPanel.tsx:341
requestAnimationFrame (async)
(anonymous) @ DiagramPanel.tsx:333
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
Show 15 more frames
000bb412:0x21df5 Uncaught RuntimeError: unreachable
    at __rust_start_panic (000bb412:0x21df5)
    at rust_panic (000bb412:0x212b5)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (000bb412:0x1ddd0)
    at std::panicking::begin_panic_handler::{{closure}}::hfa40135feb109919 (000bb412:0x1eba3)
    at std::sys_common::backtrace::__rust_end_short_backtrace::haf21bfec9a028e09 (000bb412:0x21d08)
    at rust_begin_unwind (000bb412:0x206b3)
    at core::panicking::panic_fmt::he4489d678d6570d5 (000bb412:0x20de6)
    at penrose_optimizer::step_until::hb07570db7346c7d9 (000bb412:0x5aad)
    at penrose_step_until (000bb412:0x1bc67)
    at penrose_step_until (penrose_optimizer.js:249:22)
```
