### ISSUE TITLE
NaN in polyline points leads to rust panic

### ISSUE THREAD

**Issue by Johnicholas** [penrose/penrose#1624]
While working on a simple Petri net diagram, I encountered a crash, which I believe is related to NaN in polyline points.

.domain:
```
type Box
type Place <: Box
type Transition <: Box
type Arrow
type Boundary

constructor Arrow(Box b1, Box b2)
predicate In(Box, Boundary)
predicate On(Box, Boundary)
predicate OnLeft(Box, Boundary)
predicate OnRight(Box, Boundary)
```

.substance:
```
Place input
Place v1
Place not_v1
Transition start
Transition stop
Place output

Arrow input_to_start := Arrow(input, start)
Arrow not_v1_to_start := Arrow(not_v1, start)
Arrow start_to_v1 := Arrow(start, v1)
Arrow v1_to_stop := Arrow(v1, stop)
Arrow stop_to_output := Arrow(stop, output)
Arrow stop_to_not_v1 := Arrow(stop, not_v1)

Boundary boundary

OnLeft(input, boundary)
In(v1, boundary)
In(not_v1, boundary)
In(start, boundary)
In(stop, boundary)
OnRight(output, boundary)

AutoLabel All
Label not_v1 "not v1"
```

.style:
```
canvas {
    width = 350
    height = 250
}

GLOBAL {
    REST_LENGTH = 100
    COLOR_BLACK = #000000ff
    COLOR_WHITE = #ffffffff
    COLOR_DEBUG = #ff0000ff
    COLOR_TRANSPARENT = #00000000
}

forall Box b {
    vec2 b.center = (?, ?)
}

forall Box b1; Box b2 {
    encourage maximal(vdist(b1.center, b2.center))
    ensure disjoint(b1.icon, b2.icon, 10)
}

forall Arrow a; Box b1; Box b2 where a := Arrow(b1, b2) {
    encourage equal(0, sqr(vdist(b1.center, b2.center) - GLOBAL.REST_LENGTH))
    a.start = closestPoint(b1.arrowTarget, b2.center)
    a.end = closestPoint(b2.arrowTarget, b2.center)
    shape a.line = Line {
        start: a.start
        end: a.end
        endArrowhead: "straight"
        strokeColor: GLOBAL.COLOR_BLACK
    }

    shape a.debugPolyline = Polyline {
        points: [a.start, (0, 0), a.end]
        endArrowhead: "straight"
        strokeColor: GLOBAL.COLOR_DEBUG
        strokeDasharray: "2 2"
    }
}

forall Place p {
    shape p.circle = Circle {
        center: p.center
        r: 30
        strokeWidth: 1
        strokeColor: GLOBAL.COLOR_BLACK
        fillColor: GLOBAL.COLOR_WHITE
    }
    shape p.icon = p.circle
    shape p.arrowTarget = p.circle
    shape p.text = Text {
        center: p.center
        string: p.label
    }
}

forall Transition t {
    shape t.rectangle = Rectangle {
        center: t.center
        width: 3
        height: 45
        fillColor: GLOBAL.COLOR_BLACK
    }
    shape t.arrowTarget = Rectangle {
        center: t.center
        width: 3
        height: 20
        fillColor: GLOBAL.COLOR_TRANSPARENT
    }
    t.arrowTarget above t.rectangle
    shape t.icon = t.rectangle
}

forall Boundary b {
    vec2 b.center = (?, ?)
    shape b.rectangle = Rectangle {
        center: b.center
        cornerRadius: 15
        strokeWidth: 1
        strokeColor: GLOBAL.COLOR_BLACK
        strokeDasharray: "10 10"
        fillColor: GLOBAL.COLOR_TRANSPARENT
    }
    encourage maximal(b.rectangle.width * b.rectangle.height)
}

forall Box box; Boundary boundary where In(box, boundary) {
    ensure contains(boundary.rectangle, box.icon, 10)
}

forall Box box; Boundary boundary where On(box, boundary) {
    ensure signedDistanceRect(rectPts(boundary.rectangle), box.center) == 1
}

forall Box box; Boundary boundary where OnLeft(box, boundary) {
    ensure box.center[0] == boundary.center[0] - boundary.rectangle.width / 2
    ensure inRange(box.center[1], boundary.center[1] - boundary.rectangle.height / 2, boundary.center[1] + boundary.rectangle.height / 2)
}

forall Box box; Boundary boundary where OnRight(box, boundary) {
    ensure box.center[0] == boundary.center[0] + boundary.rectangle.width / 2
    ensure inRange(box.center[1], boundary.center[1] - boundary.rectangle.height / 2, boundary.center[1] + boundary.rectangle.height / 2)
}
```

At least on my computer the panic occurs immediately and reproducibly, with an error message in the console reading:
```
Error: <polyline> attribute points: Expected number, "…8760774,175,125,NaN,NaN".
TFe @ index-0629f25b.js:280
ZLt @ index-0629f25b.js:308
tEt @ index-0629f25b.js:308
eV @ index-0629f25b.js:308
yFe @ index-0629f25b.js:308
index-0629f25b.js:190 panicked at 'NaN in xs', packages/optimizer/src/lib.rs:353:17

Stack:

Error
    at n.wbg.__wbg_new_abda76e883ba8a5f (https://penrose.cs.cmu.edu/try/assets/index-0629f25b.js:190:3028)
    at console_error_panic_hook::hook::hcefd4cc281690f23 (wasm://wasm/000ab8ce:wasm-function[111]:0x15cdd)
    at core::ops::function::Fn::call::hfa821b8726737154 (wasm://wasm/000ab8ce:wasm-function[430]:0x1eae1)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (wasm://wasm/000ab8ce:wasm-function[185]:0x1b5ea)
    at std::panicking::begin_panic_handler::{{closure}}::h0d169fa297411d6d (wasm://wasm/000ab8ce:wasm-function[204]:0x1c3c3)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h7fe51fb4d3ba6060 (wasm://wasm/000ab8ce:wasm-function[425]:0x1eab8)
    at rust_begin_unwind (wasm://wasm/000ab8ce:wasm-function[244]:0x1d5b1)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (wasm://wasm/000ab8ce:wasm-function[267]:0x1dc4a)
    at penrose_optimizer::lbfgs::step_until::h20ed929a5753cbd9 (wasm://wasm/000ab8ce:wasm-function[55]:0x26a0)
    at penrose_step_until (wasm://wasm/000ab8ce:wasm-function[56]:0x3a5f)


n.wbg.__wbg_error_f851667af71bcfc6 @ index-0629f25b.js:190
$console_error_panic_hook::hook::hcefd4cc281690f23 @ 000ab8ce:0x15daf
$core::ops::function::Fn::call::hfa821b8726737154 @ 000ab8ce:0x1eae1
$std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 @ 000ab8ce:0x1b5ea
$std::panicking::begin_panic_handler::{{closure}}::h0d169fa297411d6d @ 000ab8ce:0x1c3c3
$std::sys_common::backtrace::__rust_end_short_backtrace::h7fe51fb4d3ba6060 @ 000ab8ce:0x1eab8
$rust_begin_unwind @ 000ab8ce:0x1d5b1
$core::panicking::panic_fmt::h2d3c5586175098d9 @ 000ab8ce:0x1dc4a
$penrose_optimizer::lbfgs::step_until::h20ed929a5753cbd9 @ 000ab8ce:0x26a0
$penrose_step_until @ 000ab8ce:0x3a5f
vft @ index-0629f25b.js:190
aNe @ index-0629f25b.js:190
C6e @ index-0629f25b.js:308
_6e @ index-0629f25b.js:308
f @ index-0629f25b.js:488
000ab8ce:0x1eb9a Uncaught RuntimeError: unreachable
    at __rust_start_panic (000ab8ce:0x1eb9a)
    at rust_panic (000ab8ce:0x1e81e)
    at std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 (000ab8ce:0x1b617)
    at std::panicking::begin_panic_handler::{{closure}}::h0d169fa297411d6d (000ab8ce:0x1c3c3)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h7fe51fb4d3ba6060 (000ab8ce:0x1eab8)
    at rust_begin_unwind (000ab8ce:0x1d5b1)
    at core::panicking::panic_fmt::h2d3c5586175098d9 (000ab8ce:0x1dc4a)
    at penrose_optimizer::lbfgs::step_until::h20ed929a5753cbd9 (000ab8ce:0x26a0)
    at penrose_step_until (000ab8ce:0x3a5f)
    at vft (index-0629f25b.js:190:394)
$__rust_start_panic @ 000ab8ce:0x1eb9a
$rust_panic @ 000ab8ce:0x1e81e
$std::panicking::rust_panic_with_hook::h6df5db7ad9f65dc8 @ 000ab8ce:0x1b617
$std::panicking::begin_panic_handler::{{closure}}::h0d169fa297411d6d @ 000ab8ce:0x1c3c3
$std::sys_common::backtrace::__rust_end_short_backtrace::h7fe51fb4d3ba6060 @ 000ab8ce:0x1eab8
$rust_begin_unwind @ 000ab8ce:0x1d5b1
$core::panicking::panic_fmt::h2d3c5586175098d9 @ 000ab8ce:0x1dc4a
$penrose_optimizer::lbfgs::step_until::h20ed929a5753cbd9 @ 000ab8ce:0x26a0
$penrose_step_until @ 000ab8ce:0x3a5f
vft @ index-0629f25b.js:190
aNe @ index-0629f25b.js:190
C6e @ index-0629f25b.js:308
_6e @ index-0629f25b.js:308
f @ index-0629f25b.js:488
index-0629f25b.js:280 Error: <polyline> attribute points: Expected number, "…3095823,175,125,NaN,NaN".
TFe @ index-0629f25b.js:280
ZLt @ index-0629f25b.js:308
tEt @ index-0629f25b.js:308
eV @ index-0629f25b.js:308
yFe @ index-0629f25b.js:308
index-0629f25b.js:280 Error: <polyline> attribute points: Expected number, "…0969384,175,125,NaN,NaN".
TFe @ index-0629f25b.js:280
ZLt @ index-0629f25b.js:308
tEt @ index-0629f25b.js:308
eV @ index-0629f25b.js:308
yFe @ index-0629f25b.js:308
index-0629f25b.js:280 Error: <polyline> attribute points: Expected number, "…0969384,175,125,NaN,NaN".
```

**Comment by wodeni** [comment]
Can reproduce and link to trio: https://penrose.cs.cmu.edu/try/?gist=15164bc2e4a9a084bf859f30e074222e. 

Also NaNs go away if these two points are replaced with just `(?, ?)`, obviously not correct but `closestPoint` might be the culprit:
```
    a.start = closestPoint(b1.arrowTarget, b2.center)
    a.end = closestPoint(b2.arrowTarget, b2.center)
```

**Comment by samestep** [comment]
Yeah, the fact that we panic when we find a NaN is a big problem, in my opinion. I think we should change the optimizer to return this as a [`Result`](https://doc.rust-lang.org/std/result/enum.Result.html) instead (which `wasm-bindgen` would automatically turn into a JavaScript exception, much better than a panic).
