### ISSUE TITLE
Running Alloy 5.0 on sets-functions branches fails

### ISSUE THREAD

**Issue by hypotext** [penrose/penrose#288]
On `sets-functions`, I added some style changes (pushed separately to `sets-functions-temp` branch). I noticed that the functions being generated didn't satisfy the logical definitions:

![Screenshot 2019-11-06 20 41 58](https://user-images.githubusercontent.com/2762356/68353449-a4bc6480-00d7-11ea-988e-14fce174c9f8.png)
![Screenshot 2019-11-06 20 41 35](https://user-images.githubusercontent.com/2762356/68353450-a4bc6480-00d7-11ea-95bb-f3d170570f2d.png)
![Screenshot 2019-11-06 20 40 51](https://user-images.githubusercontent.com/2762356/68353452-a4bc6480-00d7-11ea-9272-5048fbb96d0e.png)
![Screenshot 2019-11-06 20 40 02](https://user-images.githubusercontent.com/2762356/68353453-a4bc6480-00d7-11ea-8c75-3b796a101193.png)

So I thought there was a problem with the plugin. Then I saw that commit 6d6daefa to sets-functions updated Alloy to 5.0, so then I thought that the string matching just wasn't working w/ new function names (?). So, I reran `make` in `examples/plugins/alloy` (which succeeded) and then put the Alloy 5.0 jar in the plugin folder and reinstalled java. However after all that I still get this error:

```
~/D/C/p/examples> 
runpenrose functions-domain/spec-function.sub functions-domain/discrete.sty functions-domain/functions.dsl > out.txt

Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/mit/csail/sdg/ast/Module : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.getMethod0(Class.java:2856)
	at java.lang.Class.getMethod(Class.java:1668)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
penrose: callCommand: java -cp "*:." AlloyPlugin (exit 1): failed
```

Thoughts @wodeni?

**Comment by wodeni** [comment]
Never seen this before. Make sure you run `make` in `examples/plugins/alloy`. Some info about my environment, which builds everything without errors:
```
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

**Comment by wodeni** [comment]
Here are the files tracked in the `alloy` folder:
```
AlloyPlugin.java
Makefile
README.md
json.jar
org.alloytools.alloy.dist.jar
```

**Comment by hypotext** [comment]
Thanks @wodeni! The solution was to update my Java version and set the most recent version in the shell. After trying a bunch of things, this is what worked:

`jenv local oracle64-1.8.0.40`

And the versions:

```
~/D/C/penrose> jenv local oracle64-1.8.0.40
~/D/C/penrose> which java
/Users/.../.jenv/shims/java
~/D/C/penrose> java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```
